### ISSUE TITLE
Feature request: Session/Total Total

### ISSUE THREAD

**Issue by erviker** [hultberg/ladekalk#1]
First of all love the idea.

is it possible to calculate the session total in NOK and a "Total Total"?

Example output:
```
Prices fetched for period 2023-02-25 02:00:00 - 2023-02-25 23:59:59
2023-02-25 12:00 - 12:59 @ 0.8986 NOK (+0.7275%)
2023-02-25 13:00 - 13:59 @ 0.8907 NOK (+0%)
2023-02-25 14:00 - 14:59 @ 0.8986 NOK (+0.7275%)
Session Average: 0.8960 NOK
Session Total: XXX NOK
----------------
Total Average: 0.8960 NOK
Total: XXX NOK
```

**Comment by hultberg** [comment]
First, I take it you like the project, thank you. :-)

Second, I like your suggestion and see the value in knowing the estimated cost. I'll put it on my todo list. :-)
